services:
  - type: web
    name: dash-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    disk:
      name: videos
      mountPath: /app/temp_videos
      sizeGB: 1
